config/routes.rb
Rails.application.routes.draw do
  resource :debit_card, only: [:new, :update]

  root to: 'debit_cards#new'
end

app/models/debit_card.rb
class DebitCard < ActiveRecord::Base
  belongs_to :user

  before_validation :normalize_card_number

  validates :user, uniqueness: true
  validates :card_number, presence: true
  validates :card_number, uniqueness: { scope: :expiration_date }
  validates :card_number, numericality: { only_integer: true }, allow_blank: true
  validates :card_number, length: { is: 16 }, allow_blank: true
  validates :expiration_date, presence: true
  validates :expiration_date, date: { after_or_equal_to: Proc.new { Date.current.beginning_of_month } }, allow_blank: true
  validates :cvv, presence: true
  validates :cvv, numericality: { only_integer: true }, allow_blank: true
  validates :cvv, length: { in: 3..4 }, allow_blank: true

  def last_4_digits
    card_number&.last(4)
  end

  def stub_perform_payment(amount)
    card_number == '4242424242424242' ? '100' : '203'
  end

  private

  def normalize_card_number
    card_number&.delete!(' ')
  end
end

app/models/debit_card_form.rb
class DebitCardForm
  include ActiveModel::Model

  EXISTING_CARD = 'existing_card'.freeze
  NEW_CARD = 'new_card'.freeze

  attr_accessor :user, :new_card, :payment_card

  validates :existing_card, presence: true, if: -> { payment_card == EXISTING_CARD }

  def new_card_attributes=(attributes)
    @new_card = DebitCard.new(attributes)
  end

  def new_card
    @new_card ||= DebitCard.new
  end

  def existing_card
    @existing_card ||= user.debit_card
  end

  def payment_card
    @payment_card ||= existing_card ? EXISTING_CARD : NEW_CARD
  end

  def save
    case payment_card
    when EXISTING_CARD
      valid?
    when NEW_CARD
      new_card.valid? && !!(user.debit_card = new_card) # Replace with the new card
    else
      false
    end
  end

  def persisted?
    true
  end
end

app/models/stripe/charge.rb
module Stripe
  class Charge
    def self.create(card:, amount:)
      case card.stub_perform_payment(amount)
      when '100'
        'Your order has been completed!'
      when '203'
        'Your payment has been declined. Please re-check with the providing bank.'
      else
        'Unexpected error has occurred. Please contact Kevin at (574) 347-5571.'
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :debit_card, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_or_create_by(first_name: 'Kevin', last_name: 'Kim')
  end

  helper_method :current_user
end

app/controllers/debit_cards_controller.rb
class DebitCardsController < ApplicationController
  def new
    @debit_card_form = DebitCardForm.new(user: current_user)
  end

  def update
    @debit_card_form = DebitCardForm.new(debit_card_form_params.merge(user: current_user))

    if @debit_card_form.save
      message = Stripe::Charge.create(card: current_user.debit_card, amount: 10_000)

      redirect_to new_debit_card_url, notice: message
    else
      render :new
    end
  end

  private

  def debit_card_form_params
    params.require(:debit_card_form).permit(:payment_card, new_card_attributes: [:card_number, :expiration_date, :cvv])
  end

  def existing_card_present?
    @debit_card_form.existing_card.present?
  end

  helper_method :existing_card_present?
end

app/helpers/application_helper.rb
module ApplicationHelper
  def expiration_date_to_human(expiration_date)
    expiration_date.strftime('%m/%Y')
  end

  def card_number_to_human(card_number)
    card_number.scan(/.{1,4}/).join(' ')
  end
end

app/views/application/_flashes.html.erb
<% if notice %>
  <div class="modal fade" data-behavior="show-modal-onload">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body text-xs-center">
          <%= notice %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/debit_cards/_new_card_form.html.erb
<% if f.object.errors.any? %>
  <div class="alert alert-warning">
    <ul class="list-unstyled mb-0">
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :card_number, class: 'form-control-label' %>
  <%= f.text_field :card_number, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :expiration_date, class: 'form-control-label d-block' %>
  <%= f.date_select :expiration_date, start_year: Date.current.year, end_year: Date.current.year + 10, use_month_numbers: true, discard_day: true, order: [:month, :year] %>
</div>

<div class="form-group">
  <%= f.label :cvv, 'CVV', class: 'form-control-label' %>
  <%= f.text_field :cvv, class: 'form-control' %>
</div>

<div class="form-group">
  <label class="form-control-label">Cardholder name</label>
  <div id="cardholder-name" class="form-control"><%= current_user.full_name %></div>
</div>

app/views/debit_cards/_preview_card_placeholder.html.erb
<div id="preview-card" class="debit-card-wrapper">
  <div class="debit-card">
    <div class="card-content">
      <div class="card-number">•••• •••• •••• ••••</div>
      <div class="card-expiry">••/••</div>
      <div class="card-name">Full Name</div>
    </div>
  </div>
</div>

app/views/debit_cards/new.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-md-6">
      <div class="card">
        <h6 class="card-header">Select a payment card</h6>

        <div class="card-block">
          <%= form_for @debit_card_form, url: debit_card_url do |f| %>
            <fieldset>
              <div class="form-check">
                <label class="form-check-label">
                  <%= f.radio_button :payment_card, DebitCardForm::EXISTING_CARD, class: 'form-check-input', disabled: !existing_card_present? %>
                  Existing card
                </label>

                <% if existing_card_present? %>
                  <%= content_tag :p, data: { behavior: 'existing-card-info', card_number: card_number_to_human(f.object.existing_card.card_number), exp_month: f.object.existing_card.expiration_date.month, exp_year: f.object.existing_card.expiration_date.year, full_name: f.object.existing_card.user.full_name } do %>
                    •••• •••• •••• <%= f.object.existing_card.last_4_digits %> (<%= expiration_date_to_human(f.object.existing_card.expiration_date) %>)
                  <% end %>
                <% end %>
              </div>

              <% if f.object.errors.any? %>
                <div class="alert alert-warning">
                  <ul class="list-unstyled mb-0">
                    <% f.object.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            </fieldset>

            <fieldset>
              <div class="form-check">
                <label class="form-check-label">
                  <%= f.radio_button :payment_card, DebitCardForm::NEW_CARD, class: 'form-check-input' %>
                  New card
                </label>
              </div>

              <%= f.fields_for :new_card do |new_card_form| %>
                <%= render 'new_card_form', f: new_card_form %>
              <% end %>
            </fieldset>

            <%= f.submit 'Checkout', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <h6 class="card-header">Preview a card</h6>

        <div class="card-block">
          <%= render 'preview_card_placeholder' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmartPay Code Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'flashes' %>

  <%= yield %>
</body>
</html>